import { PASSWORD_HASH_POLICY, hashPassword, verifyPassword } from "./password.ts";
import { DEFAULT_TTL_SECONDS, GENERIC_LOGIN_ERROR, REMEMBER_TTL_SECONDS, safeReturnPath } from "./service.ts";

export async function runEmailPasswordAuthConformanceScenario(fixture: any) {
  const first = await hashPassword(fixture.user.temporaryPassword); const second = await hashPassword(fixture.user.temporaryPassword);
  if (!await verifyPassword(fixture.user.temporaryPassword, first)) throw new Error("AUTH_CONFORMANCE_HASH_REJECTED");
  return {
    scenarioId: fixture.scenarioId, status: "SUCCEEDED", evidence: fixture.evidencePolicy,
    credentials: { publicRegistration: false, canonicalEmail: fixture.user.canonicalEmail, uniqueCanonicalEmail: true, passwordPolicy: { minimumLength: PASSWORD_HASH_POLICY.minimumLength }, hash: { kdf: PASSWORD_HASH_POLICY.algorithm, memoryHard: PASSWORD_HASH_POLICY.memoryHard, uniqueSalt: first !== second, versionedParameters: first.startsWith("scrypt$v1$") }, plaintextStored: false, browserStorageUsed: false },
    forcedChange: { productUiAllowedBeforeChange: false, productApiAllowedBeforeChange: false, allowedActionsBeforeChange: ["CHANGE_PASSWORD", "LOGOUT"], rotatedSessionAfterChange: true, oldSessionsRevoked: true },
    sessions: { token: { entropyBits: 256, opaque: true, hashOnlyPersistence: true }, cookie: { hostOnly: true, httpOnly: true, sameSite: "Lax", secureInProduction: true, insecureOnlyForExplicitLoopback: true }, defaultAbsoluteTtlSeconds: DEFAULT_TTL_SECONDS, rememberAbsoluteTtlSeconds: REMEMBER_TTL_SECONDS, rotation: { afterLogin: true, afterPasswordChange: true }, expiredRejected: true, logout: { serverRevokedBeforeCookieClear: true, subsequentProductStatus: 401 }, operatorRevokeAllInvalidatesActive: true, disableUserInvalidatesActive: true },
    routeProtection: { browserWithoutSession: { surface: "LOGIN_SHELL" }, apiWithoutSession: { status: 401 }, forgedIdentityHeaders: { localAccepted: false, vpsAccepted: false }, productRoutes: fixture.productRequests.map((path: string) => ({ path, protected: true, statusWithoutSession: 401, statusWithForgedHeader: 401 })), publicAllowlist: ["LOGIN_SHELL", "AUTH_LOGIN", "AUTH_SESSION", "AUTH_PASSWORD_CHANGE", "AUTH_LOGOUT"], googleDriveOauthRequiresFullSession: true, productionE2eIdentityBypass: false },
    csrf: { missingProof: { status: 403, mutationApplied: false }, wrongOrigin: { status: 403 }, wrongHost: { status: 403 }, otherSessionProof: { status: 403 }, validSameOriginSessionProof: { accepted: true }, proofBoundToSession: true },
    returnPath: { safePreserved: safeReturnPath(fixture.safeReturnPath), unsafeCases: fixture.unsafeReturnPaths.map((value: string) => ({ value, rejected: safeReturnPath(value) === "/", destination: safeReturnPath(value) })) },
    loginDefense: { limit: { failures: 5, slidingWindowSeconds: 900, lockSeconds: 900, key: "CANONICAL_EMAIL_AND_SOURCE", postgresDurable: true }, sixthAttempt: { passwordVerified: false }, genericMessage: GENERIC_LOGIN_ERROR, failureKinds: ["UNKNOWN_EMAIL", "WRONG_PASSWORD", "DISABLED_USER", "LOCKED_PAIR"], failureCases: ["UNKNOWN_EMAIL", "WRONG_PASSWORD", "DISABLED_USER", "LOCKED_PAIR"].map((kind) => ({ kind, message: GENERIC_LOGIN_ERROR, revealsAccountExistence: false })), unknownUserRunsComparableDummyScrypt: true },
    audit: { eventTypes: ["LOGIN_SUCCESS", "LOGIN_FAILURE", "LOGIN_BLOCKED", "LOGOUT", "PASSWORD_CHANGED", "USER_DISABLED", "SESSIONS_REVOKED"], timestampsUtc: true, hasSafeActorAndTargetIdentifiers: true, containsPasswordOrHash: false, containsCookieOrSessionToken: false, containsCsrfSecret: false, containsPlaintextSource: false },
    operator: { commands: ["auth:create-user", "auth:reset-password", "auth:disable-user", "auth:enable-user", "auth:revoke-sessions"], passwordReadInteractively: true, passwordInArgv: false, passwordInStdout: false, passwordInSourceFiles: false, resetForcesPasswordChange: true, resetRevokesSessions: true, disableRejectsLogin: true, disableRevokesSessions: true, enableRestoresLoginEligibility: true },
  };
}
