import { createHash, randomUUID } from "node:crypto";
import { PostgresAgentRuntimeRepository } from "../../../../../server/agent-runtime/postgres-runtime-repository.ts";
import { requestPrincipal } from "../../../../../server/auth/request-principal.ts";
import { serverContainer } from "../../../../../server/configuration/container.ts";
import { createGoogleDriveOAuthRuntime } from "../../../../../server/google-drive-oauth/runtime.ts";
import { PostgresBlobStore } from "../../../../../server/storage/blob-store.ts";
import { withTransaction } from "../../../../../server/storage/postgres.ts";

const headers = { "cache-control": "private, no-store", "x-content-type-options": "nosniff" }; const maxFixtureBytes = 24 * 1024 * 1024;
function equalSecret(actual: string, expected: unknown) { if (typeof expected !== "string" || !expected || actual.length !== expected.length) return false; let difference=0; for(let i=0;i<actual.length;i+=1) difference|=actual.charCodeAt(i)^expected.charCodeAt(i); return difference===0; }
function decodeFixture(value: unknown, code: string) { if (typeof value !== "string" || !value || value.length > Math.ceil(maxFixtureBytes*4/3)+8) throw new Error(code); const bytes=new Uint8Array(Buffer.from(value,"base64")); if(!bytes.byteLength||bytes.byteLength>maxFixtureBytes) throw new Error(code); return bytes; }
function checksum(bytes: Uint8Array) { return createHash("sha256").update(bytes).digest("hex"); }
type SmokeDetails={runId:string;vacancyId:string;candidatePk:number;folderIds:string[];fileIds:string[];operationIdentities:string[]};

export async function POST(request: Request) {
  if (!await requestPrincipal(request)) return Response.json({ready:false,code:"HR_IDENTITY_MISSING"},{status:401,headers});
  const container=await serverContainer(); const env=container.environment;
  if(env.E2E_ENVIRONMENT!=="local") return Response.json({ready:false,code:"LOCAL_SHADOW_SMOKE_ONLY"},{status:403,headers});
  const supplied=request.headers.get("authorization")?.replace(/^Bearer\s+/i,"")??""; if(!equalSecret(supplied,env.AGENT_RUNTIME_INTERNAL_TOKEN)) return Response.json({ready:false,code:"LOCAL_SHADOW_SMOKE_UNAUTHORIZED"},{status:401,headers});
  const details=async(handle:string)=>{const rows=await container.sql<{details:string}[]>`SELECT details FROM audit_events WHERE id=${handle} AND action='shadow-smoke' AND actor='local-smoke'`;if(!rows[0])throw new Error("SHADOW_SMOKE_HANDLE_NOT_FOUND");return JSON.parse(rows[0].details) as SmokeDetails;};
  try {
    const body=await request.json() as Record<string,unknown>; const action=String(body.action??"");
    if(action==="status"){
      const stored=await details(String(body.handle??""));
      const [tasks,runs,published,sent]=await Promise.all([
        container.sql<Record<string,unknown>[]>`SELECT task.task_key,task.state,attempt.error_code FROM agent_tasks task LEFT JOIN agent_attempts attempt ON attempt.task_id=task.id AND attempt.attempt_number=task.attempt_count WHERE task.run_id=${stored.runId} ORDER BY task.id`,
        container.sql<{state:string}[]>`SELECT state FROM agent_runs WHERE id=${stored.runId}`,
        container.sql<{count:number}[]>`SELECT count(*)::integer AS count FROM candidate_report_documents document JOIN candidate_report_versions version ON version.id=document.report_version_id WHERE version.run_id=${stored.runId} AND document.drive_file_id IS NOT NULL`,
        container.sql<{count:number}[]>`SELECT count(*)::integer AS count FROM candidate_notification_deliveries delivery JOIN candidate_notification_events event ON event.id=delivery.event_id WHERE event.run_id=${stored.runId} AND delivery.state='SENT'`]);
      return Response.json({ready:true,runState:runs[0]?.state??"MISSING",tasks:tasks.map((task)=>({key:String(task.task_key),state:String(task.state),...(task.error_code?{safeCode:String(task.error_code)}:{})})),effects:{publishedDocumentCount:published[0]?.count??0,sentNotificationCount:sent[0]?.count??0}},{headers});
    }
    const runtime=createGoogleDriveOAuthRuntime({database:container.sql,environment:env});
    if(action==="cleanup"){
      const handle=String(body.handle??"");const stored=await details(handle);const drive=await runtime.drive();const connection=await runtime.repository.getConnection();
      const descendants=connection&&stored.folderIds[1]?await container.sql<{file_id:string;operation_identity:string;depth:number}[]>`WITH RECURSIVE tree(file_id,depth) AS (SELECT ${stored.folderIds[1]},0 UNION ALL SELECT object.file_id,tree.depth+1 FROM google_drive_registered_objects object JOIN tree ON object.parent_id=tree.file_id WHERE object.connection_id=${connection.id} AND tree.depth<32) SELECT object.file_id,object.operation_identity,tree.depth FROM tree JOIN google_drive_registered_objects object ON object.connection_id=${connection.id} AND object.file_id=tree.file_id WHERE object.operation_identity IS NOT NULL ORDER BY tree.depth DESC`:[];
      for(const object of descendants) await drive.removeCreatedObject({fileId:object.file_id,operationIdentity:object.operation_identity}).catch(()=>undefined);
      if(stored.folderIds[0]&&stored.operationIdentities[2]) await drive.removeCreatedObject({fileId:stored.folderIds[0],operationIdentity:stored.operationIdentities[2]}).catch(()=>undefined);
      const blobs=new PostgresBlobStore(container.sql); await blobs.deleteScope(`candidate:${stored.candidatePk}:run:${stored.runId}`,true);
      await withTransaction(container.sql,async transaction=>{await transaction`DELETE FROM candidates WHERE id=${stored.candidatePk}`;await transaction`DELETE FROM vacancies WHERE id=${stored.vacancyId}`;await transaction`DELETE FROM audit_events WHERE id=${handle}`;});
      return Response.json({ready:true,cleanup:{drive:true,postgresql:true,blob:true,provider:true}},{headers});
    }
    if(action!=="provision") throw new Error("SHADOW_SMOKE_ACTION_INVALID"); const requestedMode=body.mode==="effectful"?"effectful":"shadow";
    if(env.CANDIDATE_TOOL_EXECUTION_MODE!=="production"||env.CANDIDATE_PIPELINE_ROUTING!==requestedMode) throw new Error("SHADOW_SMOKE_RUNTIME_MODE_INVALID");
    const resume=decodeFixture(body.resumeBase64,"SHADOW_SMOKE_RESUME_INVALID");const interview=decodeFixture(body.interviewBase64,"SHADOW_SMOKE_INTERVIEW_INVALID");const connection=await runtime.repository.getConnection();if(!connection||connection.state!=="CONNECTED")throw new Error("GOOGLE_DRIVE_REAUTH_REQUIRED");const drive=await runtime.drive();
    const nonce=randomUUID();const identities=[`shadow-smoke:${nonce}:resume`,`shadow-smoke:${nonce}:interview`,`shadow-smoke:${nonce}:vacancy-folder`,`shadow-smoke:${nonce}:candidate-folder`];const folderIds:string[]=[];const fileIds:string[]=[];
    try{
      const vacancyFolder=await drive.ensureFolder({name:`.hh-shadow-${nonce.slice(0,8)}`,parentFolderId:connection.rootFolderId,operationIdentity:identities[2]});folderIds.push(vacancyFolder.id);const candidateFolder=await drive.ensureFolder({name:"Синтетический кандидат",parentFolderId:vacancyFolder.id,operationIdentity:identities[3]});folderIds.push(candidateFolder.id);
      fileIds.push((await drive.putFile({parentFolderId:candidateFolder.id,fileName:"synthetic-resume.pdf",mimeType:"application/pdf",bytes:resume,checksum:checksum(resume),operationIdentity:identities[0]})).id);fileIds.push((await drive.putFile({parentFolderId:candidateFolder.id,fileName:"synthetic-interview.wav",mimeType:"audio/wav",bytes:interview,checksum:checksum(interview),operationIdentity:identities[1]})).id);
      let previous="",stable=0;for(let attempt=0;attempt<15&&stable<3;attempt+=1){const objects=await drive.listChildren(candidateFolder.id);const fingerprint=checksum(new TextEncoder().encode(JSON.stringify(objects.map(object=>({fileId:object.fileId,version:object.version,size:object.size,modifiedTime:object.modifiedTime})).sort((a,b)=>a.fileId.localeCompare(b.fileId)))));stable=fingerprint===previous?stable+1:0;previous=fingerprint;if(stable<3)await new Promise(resolve=>setTimeout(resolve,2000));}if(stable<3)throw new Error("SHADOW_SMOKE_DRIVE_NOT_STABLE");
      const vacancyId=`vacancy-shadow-${nonce}`,candidatePublicId=`candidate-shadow-${nonce}`,inputVersion=`input-shadow-${nonce}`,runId=`run-shadow-${nonce}`,goalId=`goal-shadow-${nonce}`,now=new Date().toISOString();
      const candidatePk=await withTransaction(container.sql,async transaction=>{await transaction`SELECT pg_advisory_xact_lock(7341108222)`;const [next]=await transaction<{value:number}[]>`SELECT COALESCE(max(id),0)::integer+1 AS value FROM candidates`;const value=next.value;const vacancy={id:vacancyId,title:"Синтетический инженер TypeScript",normalizedTitle:`shadow-${nonce}`,active:true,version:1,templateVersion:"synthetic-shadow/v1",driveFolderId:vacancyFolder.id,profile:{requiredExperience:"TypeScript и измеримый результат",desiredExperience:"Работа с сервисами",accessToKe:"Умеет проверять результат"},abcDirections:[{id:"direction-a",title:"Результат",description:"Подтверждённый измеримый результат",weight:1}]};const candidate={id:candidatePublicId,name:"Синтетический кандидат",initials:"СК",vacancyId,vacancy:vacancy.title,status:"NEW",archived:false,stageStartedAt:now,elapsedMinutes:0,etaMinutes:null,result:null};await transaction`INSERT INTO vacancies(id,normalized_title,record_json)VALUES(${vacancyId},${vacancy.normalizedTitle},${JSON.stringify(vacancy)})`;await transaction`INSERT INTO candidates(id,public_id,revision,record_json)VALUES(${value},${candidatePublicId},1,${JSON.stringify(candidate)})`;await transaction`INSERT INTO candidate_drive_folders(drive_folder_id,candidate_id,vacancy_folder_id,display_name,parent_path,first_seen_at_utc,last_seen_at_utc)VALUES(${candidateFolder.id},${value},${vacancyFolder.id},${candidate.name},${`Найм/${vacancy.title}/${candidate.name}`},${now},${now})`;return value;});
      await new PostgresAgentRuntimeRepository(container.sql).createGoal({goalId,runId,candidateId:candidatePk,goalType:"candidate-analysis/v1",inputVersion,profileVersion:`${vacancyId}:v1`,policyVersion:"candidate-policy-v1",completionCriteriaVersion:"candidate-completion-v1",completionCriteria:["validated-assessment","shadow-effects-suppressed"],budgets:{wallTimeMs:1800000,taskAttempts:40,repairAttempts:2,replans:2,llmCalls:24,tokens:250000,costMicrounits:5000000,externalRequests:120},triggerIdentity:`shadow-smoke:${nonce}`});
      const handle=randomUUID();const stored:SmokeDetails={runId,vacancyId,candidatePk,folderIds,fileIds,operationIdentities:identities};await container.sql`INSERT INTO audit_events(id,candidate_id,action,actor,timestamp,outcome,details)VALUES(${handle},${candidatePk},'shadow-smoke','local-smoke',${now},'ACTIVE',${JSON.stringify(stored)})`;return Response.json({ready:true,handle,state:"ACTIVE"},{headers});
    }catch(error){for(let i=fileIds.length-1;i>=0;i-=1)await drive.removeCreatedObject({fileId:fileIds[i],operationIdentity:identities[i]}).catch(()=>undefined);for(let i=folderIds.length-1;i>=0;i-=1)await drive.removeCreatedObject({fileId:folderIds[i],operationIdentity:identities[i+2]}).catch(()=>undefined);throw error;}
  }catch(error){const code=error instanceof Error&&/^[A-Z0-9_:.-]+$/.test(error.message)?error.message:"SHADOW_SMOKE_FAILED";return Response.json({ready:false,code},{status:422,headers});}
}
